name: Deploy Firebase Functions Manually

on:
  workflow_dispatch:

jobs:
  deploy_functions:
    name: Deploy Functions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Create firebaseConfig.json for Project ID extraction
        run: echo '${{ secrets.FIREBASE_CONFIG_JSON }}' > src/firebaseConfig.json

      - name: Install jq and Extract Project ID
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          PROJECT_ID=$(jq -r '.projectId' src/firebaseConfig.json)
          if [ -z "$PROJECT_ID" ] || [ "$PROJECT_ID" == "null" ]; then
            echo "Error: projectId could not be extracted from FIREBASE_CONFIG_JSON."
            exit 1
          fi
          echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_AGENT_WEB_UI }}

      - name: Prepare Python Env
        working-directory: ./functions
        run: |
          python3.11 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy Firebase Functions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
        run: |
          echo "Deploying Functions to project: ${{ env.PROJECT_ID }}"
          firebase deploy --only functions --project ${{ env.PROJECT_ID }} --force --source ./functions

      - name: Clean up config file
        if: always()
        run: rm -f src/firebaseConfig.json
